import pandas as pd
import re

menu = pd.read_csv("../01_openrefine/Menu_clean.csv.gz", compression='gzip')
menu.fillna('', inplace=True)

def mapEventToMeal(E):
    # Manual label overrides
    event = set(
        [
'paas festival',
'convention',
'wedding',
'shakepeare commemoration',
'personally conducted tour through mexico & california',
'avviversary of the boston massacre',
'special lenten dishes',
'41 jahres versammlung',
'54th annual regatta',
'examination paper',
'complimentary to mr. w.h.metson,prior to his departure for cape nome,alaska',
'new years eve',
'presidential tour to the pacific coast, april 29-june 15, 1901',
'pan-american restaurant co.',
'in honor of our veterans',
'fourth of july',
'fourth of july menu',
'quarterly membership meeting',
'en route to boston and return',
'presidential tour to the pacific coast',
'ninth annual lawn party',
'official visit of inspection of illustrious potentate charles a. benedict',
'inernational yacht races',
'see above',
'second meeting of above',
'9nth danzinger martini fest',
'specials of day',
'sunday tea',
'winkelried-auffuhrungen',
'15th annual conventin',
'erbsensuppe',
'menus for special train to episcopal convention in san francisco, oct. 2, 1901',
'goldenes jubilaeum (golden jubilee)',
'centennial celebration',
'lawn party & band concert',
'one hundred and fiftieth annivesary',
'pan american exposition',
'dibnner to edward m. grout',
'convention of superintendents',
'in honor of mr. hall caine',
'musicale & cotillion at cordova tonight',
'twenty-fifth annivesay o founding of club',
'second annual convention',
'vaudeville entertainment',
'30th annual meeting',
'eleventh annual convenion',
'20th annual meeting',
'in convivial session',
'ninth annual banquest and meeting',
'dedication',
'268 fall field day',
'inauguration day',
'thirteenth annual meeting',
'60 versammlung',
'liedertafel',
'in commemoration of the 73rd birthday of general grant',
'launching of the "saturday night"',
'saint nicholas day',
'to the captain & officers of h.n.m.ss van speijk',
"jefferson's birthday guest of honor william jennings bryan",
'thanksgiving day menu & program',
'easter sunday',
'tenth burns annivesary',
'dance',
'relig;',
'20th meeting',
'19th annual meeting',
'first meeting',
'general menu',
'peace jubilee',
'festessen zu ehren des 70 geburtstages von carl schurz',
'in honor of arthur henry meissiter,musical director',
'74th bithday of u.s. grant',
'excursion around the harbor of new york for the miller national association',
'cafe service',
'queen victoria''s birthday',
'banquest o the british fisheries commission',
'opening celebration for steamer sam sloan',
'st. patrick''s day',
'centennial celebration of the first settlement in ohio valley',
'trip to jamestown, va[ for hotel men''s mutual benefit association of the united states and canada',
'one hundred and third regular meeting',
'for the conseil federal suisse',
'127th annual meeting',
'new year buffet',
'17th annual festival',
'daily specials',
'probe-bankett',
'fauste nozze della caro figlia colomba rosa col sig. luigi profumo',
'directed by signor caioli luigi',
'extras for today menu;',
'annual festival',
'59th convention',
'opening of egyptian hall',
'national convention',
'testimonial to m.e. frederick e. barnes past grand high priest',
'old-fashioned rhode island clam bake',
'in commemoration of the birthday of abraham lincoln',
'bon voyage to mr. james pollock',
'twelfth annual meeting',
'opening of the hotel',
'fifty third annivrsary',
'to victor s. herbert & the pittsburgh orchestra',
'celebration of the evacuation of the city of new york',
'washingt0n''s birthday',
'picnic(?)',
'automobile night',
'53rd annual regatta',
'decimo aniversario de la revista de medicina y cerugia de la habana',
'94th anniv.',
'special menu',
'261st fall field day',
'no. iv of five subscription cotillions',
'presentation of sword to capt.a.c. braden',
'commemoration of the birthdaay of abraham lincoln',
'special dishes of to-day',
'arrival of the raleigh from manila',
'feast of saint john the evangelist',
'celebration of opening',
'in honour of national wholesale lumber dealers association',
'173rd regular meeting',
'fourth annual convention',
'mardi gras bal masque',
'banquest to ferdinand w. peck, commissioner of u.s.a. to paris exposition',
'stiftungsfest',
'florida golf association tournament',
'almuerzo',
'59th meeting',
'34th annual celebration',
'fourth annual meeting',
'20th annual social session, free to stockholders',
'clio menu',
'forefathers day',
'launching of ferryboat richmond',
'93rd regular meeting',
'126th annual meeting',
'raymond excursion party',
'launching of above',
'122nd annual meal',
'hunting menu to ministers of france',
'farewell to gen. horace porter, u.s. ambassador to the republic of france',
'atlas club minstrels',
'thanksgiving menu',
'96s decennial',
'wedding of wilhelmina zeisse and aloys schaufler',
'compl.',
'seventh annual festival',
'great surprise, the',
'box at ascot races',
'formal opening of the new house',
'meal for the members of terrace bowling club',
'daily menu, tea',
'collation to hotel men''s mutual benefit association',
'deed to h.m. howard',
'decennial celebration',
'second annual dance',
'opening collation',
'[general',
'lincheon',
'128th annual meeting',
'smoker',
'dining car service',
'annual outbreak',
'260th fall field day',
'dining room menu',
'governors'' day',
'3rd annual convention',
'102nd regular meeting',
'in honor of chief petty officers of h.m.s. drake',
'twenty- seventh annual meeting',
'dedication of mill of fall river iron works co. fall river, ma;',
'u.s.grant''s birthday',
'1899/11/09',
'natal day greeting',
'commemoration of the pilgrim''s statue unveiling',
'sechsten zusammenkunst',
'farewell to old delmonico''s',
'wedding day',
'hochzeitessen von herrn rechtsanwalt max guttmann und fraulein bertha lenpold',
'st. nicholas day, 1892',
'29th annual meeting',
'glefid',
'jubilee fete',
'complimentary to b.w. rowell, illustrious imperial recorder of imperial council of north america',
'semi-centennial of opening',
'symposium',
'lincoln night',
'visit of colonial prime ministers to the city of london',
'eleventh meeting',
'glorification oa william henry jackson',
'table d''hote de bon vivant',
'95th regular meeting',
'297th meeting',
'daily cafe menu',
'christmas dinnr',
'eighteenth annual convention',
'seventeenth annual social session',
'menu new year 1892',
'23rd annual meeting',
'collation on new year''s eve to his patrons',
'tariff',
'honoring james m. barrie and w. robertson nicoll',
'festessen zur feier des geburtstag sr.maj. kaiser wilhelm ii',
'thanksgiving day menu',
'1900s sexennial',
'opening day of new rooms',
'inauguration of mr. alderman alliston & lieut. col. clifford probyn, v.d.',
'meal for wedding celebration',
'258th fall field day',
'one hundredth aniversary of establishment of court',
'mayors'' day',
'second convention sales department',
'au revoir to mr. frank d. lalanne',
'reopening of club',
'ninth annual-in honor of crow charlton',
'souvenir menu',
'fifty-eighth meeting',
'commem. of evacuation of nyc by the british',
'third annual convention',
'schweinessen (pig eating?)',
'in commemoration of our late companion and commander general wallace',
'ramadhan snack menu',
'pre theatre',
'royal hotel white horse rangoon whiskey menu',
'inauguration of the oklahome chapter',
"queen victoria's birthday",
"[st. patrick's day?]",
"trip to jamestown, va[ for hotel men's mutual benefit association of the united states and canada]",
"daily menu, five o'clock tea",
"washingt0n's birthday",
"chef's tasting menu",
'"clio" menu'
"collation to hotel men's mutual benefit association",
'"deed to h.m. howard"',
'dinner', 'lunch', 'event',
"[general] grant's birthday",
'"annual outbreak"',
"governors' day",
"u.s.grant's birthday",
"commemoration of the pilgrim's statue unveiling",
"'farewell to old delmonico's",
'[birthday of princess thyra of denmark]',
"collation on new year's eve to his patrons",
"mayors' day",
"collation to hotel men's mutual benefit association",
"menu aboard ss barbarossa"])
    
    unk = "Unknown Meal for Event"
    
    # Convert to lower case and trim
    e = str(E).lower().strip()    
    result = []
    if re.search("(evening menu|dinner|diner|supper|dinne|fest-bankett|banquet|dnner|dinnwe|abendessen|dinhner|dinnner|evening meal|abend-essen|souper|hauptmahlzeit|banchetto)", e) != None: result.append("dinner")
    if re.search("(lunch|luncheon|dejeuner|mittagessen|mittagesses|midday meal|mittagesen|mitagessen|noonday meal|brunch|mittag-essen|daily menu - 11;30 to 3;00|daily menu - 11;30 t0 3;00|sandwich list|midday fare|a regular saturday afternoon deal)", e) != None: result.append("lunch")
    if re.search("(\btea\b|tiffin|tea menu|afternoon tea)", e) != None: result.append("tea")
    if re.search("(breakfast|brealfast|breakdast|breakast|fruhstuck|morning meal|fruhstuck|brunch|breakrfast)", e) != None: result.append("breakfast")
    if re.search("(dessert)", e) != None: result.append("dessert")
    if re.search("(wine list|beverage list|beverages|bar menu|cocktails|a selection of table wines|champagnes list|caviar and drink menu|drinks and snacks)", e) != None: result.append("wine list")        
    if re.search("(cafe \& restaurant menu|daily menu|\"clio\" menu|daily menus|daily menu and rates|^seafood$|^buffet$|day\'s menu|german\-african menu|complete menu|menu for all meals|spisenfolge|speisenfolge|regular menu|bill of fare|daily bill of fare|carte du jour|a la carte|speike-karte|speise-karte|speise karte|daily hotel menu|d\'hote|sunday menu|cafe service|dining car service meals|room service|third class menu|daily price list)", e) != None: result.append("menu")
    if re.search("(ball|reception|washington|anniversary|ladies night|reunion|outing|annual meeting)", e) != None: result.append("Unknown Meal for Event")
    if result == []:
        if e in event: result.append(unk)
        else: result.append(E)

    # Clean up where multiple patterns hit
    if "dinner" in result:
        if unk in result: result.remove(unk)
        if "menu" in result: result.remove("menu")
   
    if "lunch" in result:
        if unk in result: result.remove(unk)
        if "menu" in result: result.remove("menu")
    
    if "breakfast" in result:
        if unk in result: result.remove(unk)
        if "menu" in result: result.remove("menu")
            
    return str(result)


def mapVenueToCleanVenue(x):
    other = set(["foreign", "other", "som;", "cam;", "conn", "dom;", "foreigneign", "unknown"])
    com = set(["com", "commercial", "comm", "com; pol", "com; soc", "commercoa;", "other: hospital (?);"])
    govt = set(["govt", "nav", "patr", "mil", "pol", "pat", "polit;", "naval", "milit;", "military",
               "other (royal king);", "other (british royal family);", "other (royal figure);",
               "other (royal host);", "other (royal monarch);", "soc, mil", "soc,pol", "soc;mil;",
               "political", "polit;", "naval", "patriotic", "milit;", "pol, soc", "military",
               'other (royal figure);', 'other (royal host);', 'other (head of royal family);',
               'other [?presumably british royal family];','soc,pol', 'soc, mil', 'other (royal monarch);',
               'other (royal king);', 'polit;', 'patr', 'pat', 'military', 'other (royal figure);',
               'other (british royal family);', 'soc;mil;', 'other (royal host);' ,'other (head of royal family);'])

    hotel = set(["hotel", "hotel,restaurant","hotel","foreign,hotel,rest","foreign,hotel","hotel; for", "foreign; hotel;",
                "hotel,other,ballroom", 'foreign,hotel,restaurant'])
    prof = set(["prof", "educ", "gov", "educational", "pro;", "educ; prof;", "edus;", "prof; com;",
                "prof;soc;", "prog;", "reporters of event"])
    rest = set(["restaurant", "resort", "restaurant,lunch room,coffee shop",
               "restaurant,other,urant,other,bar", "foreign,restaurant"])
    vessel = set(["railroad", "steamship", "airline", "ss; for", "foreign,railroad"])
    
    results = []
    if x in other: results.append("other")
    if x in com: results.append("com")
    if x in hotel: results.append("hotel")
    if x in prof: results.append("prof")
    if x in rest: results.append("restaurant")
    if x in vessel: results.append("vessel")
        
    if results == [] and x != "": results.append("soc")
    return str(results)

def cleanPlace(x, key):
    manualClean = {
    "new york":("New York City, New York, US","NA"),
"en route":("en route","Unknown"),
"delmonico's ny":("56 Beaver St, New York, NY 10004, US",""),
"en route aboard hong kong maru":("en route","Maru"),
"ss \"friedrich der grosse\"":("en route","SS friedrich der grosse"),
"en route aboard ss. kasuga":("en route","SS Kasuga"),
"?":("Unknown","NA"),
"ny":("New York City, New York, US","NA"),
"tampa, fl":("Tampa, Florida, US",""),
"schnelldampfer \"auguste victoria\"":("en route","SS Auguste Victoria"),
"ss city of para":("en route","SS City of Para"),
"st. augustine, fl":("St. Augustine, Florida, US","NA"),
"ss city of rio de janeiro":("en route","SS City of Rio de Janeiro"),
"ss furst bismarck":("en route","SS Furst Bismarck"),
"ss sonoma":("en route","SS Sonoma"),
"tampa,fla.":("Tampa, Florida, US","NA"),
"chicago":("Chicago, IL, US","NA"),
"ss auguste victoria":("en route","SS Auguste Victoria"),
"an bord der \"amerika\"":("en route","Amerika"),
"schnelldampfer \"hohenzollern\"":("en route","SS Hohenzollern"),
"ss westernland":("en route","Westernland"),
"en route aboard ss hong kong maru":("en route","Hong Kong Maru"),
"ss barbarossa":("en route","SS Barbarossa"),
"miami biscayne bay, fl":("Miami Biscayne Bay, Florida, US","NA"),
"dampfer \"barbarossa\"":("Miami Biscayne Bay, Florida, US","NA"),
"ss doric":("en route","SS Doric"),
"en route aboard sonoma":("en route","Sonoma"),
"washington d.c.":("Washington D.C., US","NA"),
"saratoga springs, ny":("Saratoga Springs, NY, US","NA"),
"en route aboard dampfer lahn":("en route","Dampfer Lahn"),
"en route aboard express steamer furst bismarck":("en route","Express Steamer Furst Bismarck"),
"st.augustine,fla.":("St. Augustine, Florida, US","NA"),
"philadelphia":("Philadelphia, PA, US","NA"),
"konigin luise":("en route","Konigin Luise"),
"ss hohenzollern":("en route","SS Hohenzollem"),
"en route aboard dampfer kronprinz wilhelm":("en route","Dampfer Kronprinz Wilhelm"),
"at sea":("en route","Unknown"),
"tampa,fl":("Tampa, Florida, US","NA"),
"ss friesland":("en route","SS Friesland"),
"delmonico's new york":("56 Beaver St, New York, NY 10004, US","NA"),
"kaiser friedrich at sea":("en route","Kaiser Friedrich"),
"park lane":("Unknown (Park Lane?)","NA"),
"detroit, mi":("Detroit, MI, US","NA"),
"narragansett pier r.i.":("Narragansett Pier, RI, US","NA"),
"on board \"new york\"":("en route","New York"),
"en route friedrich der grosse":("en route","Friedrich der Grosse"),
"rms campania":("en route","RMS Campania"),
"new york city":("New York City, New York, US","NA"),
"en route s.s. zeeland":("en route","SS Zeeland"),
"dining car":("en route","Unknown (Train)"),
"en route aboard ss. kamakura maru":("en route","SS Kamakura Maru"),
"southern pacific":("en route","Southern Pacific"),
"delmonico's":("56 Beaver St, New York, NY 10004, US","NA"),
"atlantic city, nj":("Atlantic City, NJ, US","NA"),
"ss coptic":("en route","SS Coptic"),
"london, england":("London, England","NA"),
"brooklyn, ny":("Brooklyn, NY, USA","NA"),
"aboard ss kamakura maru":("en route","SS Kamakura Maru"),
"en route aboard dampfer friedrich der grosse":("en route","Dampfer Friedrich der Grosse"),
"st.augustine,fl":("St. Augustine, Florida, US","NA"),
"boston, ma":("Boston, MA, US","NA"),
"ss gaelic":("en route","SS Gaelic"),
"cleveland, oh":("Cleveland, OH, USA","NA"),
"dampfer \"kronprinz wilhlem\"":("en route","Dampfer Kronprinz Wilhelm"),
"hotel manhattan, ny":("Hotel Manhattan, New York City, New York, US","NA"),
"rms oceanic":("en route","RMS Oceanic"),
"sherry's ny":("Sherry's (Unknown), New York City, NY","NA"),
"paris, france":("Paris, France","NA"),
"en route aboard ventura":("en route","Ventura"),
"the new willard, washington dc":("The New Willard, Washingon D.C., US","NA"),
"altoona, pa":("Altoona, PA, USA","NA"),
"en route aboard dampfer barbarossa":("en route","Dampfer Barbarossa"),
"r.m.s. lucania":("en route","RMS Lucania"),
"chicago, ill":("Chicago, IL, US","NA"),
"en route aboard ss kobe maru":("en route","SS Kobe Maru"),
"en route aboard ss.k0be maru":("en route","SS Kobe Maru"),
"en route s.s.zeeland":("en route","SS Zeeland"),
"schnelldampfer (express steamer) august victoria":("en route","August Victoria"),
"ss kronprinz wilhelm":("en route","SS Kronprinz Wilhelm"),
"steamship kaiser wilhelm der grosse":("en route","Kaiser Wilhelm der Grosse"),
"nassau,bahamas":("Nassau, Bahamas","NA"),
"gramercy park hotel":("Gramercy Park Hotel, Unknown","NA"),
"ss rio de janeiro":("en route","SS Rio de Janeiro"),
"u.s.m.s. new york":("en route","USMS New York"),
"st. louis, mo":("St. Louis, MO, US","NA"),
"jacksonville, fl":("Jacksonville, FL, US","NA"),
"quebec, canada":("Quebec, Canada","NA"),
"los angeles, ca":("Los Angelas, CA, US","NA"),
"waldorf-astoria, new york":("Waldorf-Astoria, New York City, New York, US","NA"),
"aboard ss kasuga;":("en route","SS Kasuga"),
"ss konigin luise":("en route","SS Konigin Luise"),
"unknown":("Unknown","Unknown"),
"coronado beach, ca":("Coronado Beach, CA, US","NA"),
"ellicott square, buffalo, ny":("Ellicott Square, Buffalo, NY, US","NA"),
"en route aboard s.s. westernland":("en route","SS Westernland"),
"old point comfort, va":("Old Point Comfort?, VA, US","NA"),
"tokyo, japan":("Tokyo, Japan","NA"),
"ss sierra":("en route","SS Sierra"),
"dining car service":("en route","Unknown (Train)"),
"ss kasuga":("en route","SS Kasuga"),
"san francisco":("San Francisco, CA, US","NA"),
"white mountains, nh":("White Mountains, NH, US","NA"),
"ss kaiser wilhelm der grosse":("en route","SS Kaiser Wilhel der Grosse"),
"auditorium hotel [chicago, il]":("Auditorium Hotel, Chicago, IL, USA","NA"),
"nassau, bahamas":("Nassau, Bahamas","NA"),
"manhattan hotel, new york, ny":("Manhattan Hotel, New York City, NY, USA","NA"),
"buffalo, ny":("Buffalo, NY","NA"),
"san francisco, ca":("San Francisco, CA, US","NA"),
"en route aboard ss friedrich der grosse":("en route","SS Friedrich der Grosse"),
"ss hong kong maru":("en route","Hong Kong Maru"),
"en route aboard furst bismarck":("en route","Furst Bismarck"),
"sunset ogden & shasta routes":("en route","Unknown (Sunset Ogden & Shasta Routes)"),
"palm beach, fl":("Palm Beach, FL, US","NA"),
"the waldorf-astoria":("The Waldorf-Astoria, New York City, NY, USA","NA"),
"providence":("Providence?","NA"),
"new orleans, la":("New Orleans, LA, US","NA"),
"sherry's, new york, ny":("Sherry's (Unknown), New York City, NY","NA"),
"waldorf-astoria":("The Waldorf-Astoria, New York City, NY, USA","NA"),
"en route - ss \"lahn\"":("en route","SS Lahn"),
"cincinnati, oh":("Cincinnati, OH, USA","NA"),
"clinton,ny":("Clinton, NY, USA","NA"),
"on board":("en route","Unknown (train)"),
"en route aboard dampfer h.h. meier":("en route","HH Meier"),
"ss deutschland":("en route","SS Deutschland"),
"schnelldampfer \"deutschland\" commodore albers":("en route","SS Deutschland"),
"en route aboard s.s. friesland":("en route","SS Friesland"),
"astor hotel, new york, ny":("Astor Hotel, New York City, NY, USA","NA"),
"lakewood, nj":("Lakewood, NJ, USA","NA"),
"park lane; 299 park avenue":("Park Lane, 299 Park Avenue, New York City, NY, USA","NA"),
"r.m.s. \"empress of china\"":("en route","RMS Empress of China"),
"en route aboard panama line steamship city of para":("en route","Panama Line City of Panama"),
"en route aboard konigin luise":("en route","Konigin Luise"),
"savoy hotel, new york, ny":("Savory Hotel, New York, NY, US","NA"),
"en route aboard s.s. zealandia":("en route","SS Zealandia"),
"montreal, canada":("Montreal, Canada","NA"),
"en route aboard kaiser wilhelm der grosse":("en route","Kaiser Wilhelm der Grosse"),
"en route aboard s.s. doric":("en route","SS Doric"),
"ritz carlton restaurant an bord der \"amerika\"":("en route","Amerika"),
"the auditorium [chicago, il]":("Auditorium Hotel, Chicago, IL, USA","NA"),
"en route aboard schnelldampfer auguste victoria":("en route","August Victoria"),
"concorde":("en route","Concorde"),
"san francisco overland limited":("en route","San Francisco Overland Limited"),
"dining car, southern pacific":("en route","Southern Pacific"),
"milwaukee, wi":("Milwaukee, WI","NA"),
"dampfer kaiser wilhelm der grosse;":("en route","Dampfer Kaiser Wilhelm der Grosse"),
"en route aboard r.m.s. empress of china":("en route","RMS Empress of China"),
"en route aboard r.m.s. lucania":("en route","RMS Lucania"),
"long beach, li [ny]":("Long Beach, New York City, New York","NA"),
"philadelphia, pa":("Philadelphia, PA, US","NA"),
"put-in-bay-island, lake erie, oh;":("Put-in-Bay Island, Lake Erie, OH, US","NA"),
"66th st and broadway,new york,ny":("66th st and Broadway, New York City, NY, US","NA"),
"ss st paul":("en route","SS St. Paul"),
"saratoga springs,ny":("Saratoga Springs, NY, US","NA"),
"sunset ogden & shasta route":("Unknown (Sunset Ogden & Shasta Route)","Unknown "),
"en route s.s.\"barbarossa\"":("en route","SS Barbarossa"),
"en route aboard dampfer friedrich der grosser":("en route","Dampfer Friedrich der Grosse"),
"en route aboard s.s.zealandia":("en route","SS Zealandia"),
"en route aboard s.s.zeeland":("en route","SS Zeeland"),
"[en route to canton?]":("en route","Unknown"),
"rome, italy":("Rome, Italy","NA"),
"aboard ss manitoba":("en route","SS Manitoba"),
"aboard kronprinzessin cecilie":("en route","Kronprinzessin Cecilie"),
"on board the ss vaderland":("en route","SS Vaderland"),
"portland, me":("Portland, ME, US","NA"),
"melbourne, australia":("Melbourne, Australia","NA"),
"nassau,n.p.bahamas":("Nassau, Bahamas","NA"),
"pullman dining car service en route":("en route","Unknown Train"),
"dampfer; h.h. meier":("en route","Dampfer H.H. Meier"),
"sonoma":("Sonoma??","NA"),
"nyc":("New York City, New York, US","NA"),
"en route s.s.vaderland":("en route","SS Vaderland"),
"clinton county, ny":("Clinton County, NY, USA","NA"),
"the pullman company - en route":("en route","Unknown (Train)"),
"aboard paquebot la lorraine":("en route","Paquebot la Lorraine"),
"en route aboard dampfer necker":("en route","Dampfer Necker"),
"ventura":("Ventura?","Unknown"),
"aboard paquebot la provence":("en route","Paquebot la Provence"),
"hotel astor":("Hoel Astor, New York, NY, US","NA"),
"on board s.s.kronprinzessin cecile":("en route","SS Kronprinzessin Cecile"),
"madison square, new york":("Madison Square, New York City, NY, US","NA"),
"[sr rr]enroute nashville to washington [dc]":("en route","Unknown"),
"nassau, n.p. bahamas":("Nassau, Bahamas","NA"),
"hotel brunswick ny":("Hotel Brunswick, New York City, NY","NA"),
"maison prunier":("Maison Prunier?","Unknown"),
"palace hotel":("Palace Hotel, San Francisco, CA","Unknown"),
"on board s.s. 'kronprinzessin cecilie'":("en route","SS Kronprinzessin Cecile"),
"r.m.s. etruria":("en route","RMS Etruria"),
"ss ventura;":("en route","SS Ventura"),
"queen city club [cincinnati, oh]":("Queen City Club, Cincinatti, OH, US","NA"),
"r.m.s. \"luncania\"":("en route","RMS Lucania"),
"hotel manhattan,ny":("Hotel Manhattan, New York City, New York, US","NA"),
"hotel savoy":("Hotel Savory","NA"),
"logan house, altoona, pa":("Logan House, Altoona, PA, US","NA"),
"en route aboard r.m.s. etruria":("en route","RMS Etruria"),
"on board ss north west":("en route","SS North West"),
"virginia beach, va":("Virgina Beach, VA, US","NA"),
"palace hotel, san francisco, ca":("Palace Hotel, San Francisco, CA","NA"),
"colorado springs, co":("Colorado Springs, CO, US","NA"),
"hotel pfister, milwaukee, wi":("Hotel Pfister, Milwaukee, WI, US","NA"),
"en route aboard city of para":("en route","City of Para"),
"zermatt, switzerland":("Zermatt, Switzerland","NA"),
"hotel astor, new york":("Hotel Astor, New York, NY, US","NA"),
"ss ventura;2nd cabin":("en route","SS Ventura"),
"ss meier":("en route","SS Meier"),
"ss: kamakura maru":("en route","SS Kamakura Maru"),
"steamship kaiser wilhelm der grosser":("en route","SS Kaiser Wilhel der Grosse"),
"broadway and 73rd street, new york":("Broadway and 73rd, New York, NY, US","NA"),
"waldorf-astoria hotel, new york, ny":("Waldorf-Astoria, New York City, New York, US","NA"),
"nassau, the bahamas":("Nassau, Bahamas","NA"),
"copenhagen, denmark":("Copenhagen, Denmark","NA"),
"57 broad street, ny":("57 Broad St., New York, NY, US","NA"),
"enroute aboard schnelldampfer (express-steamer) furst bismarck":("en route","SS Furst Bismarck"),
"aboard s.s. friesland":("en route","SS Friesland"),
"boston,mass":("Boston, MA, US","NA"),
"hotel somerset, boston, ma":("Hotel Somerset, Boston, MA, US","NA"),
"union league":("Union League?","NA"),
"miami biscayne bay,fla.":("Biscayne Bay, Miami, FL, US","NA"),
"waldorf-astoria, ny":("Waldorf-Astoria, New York City, New York, US","NA"),
"on board \"c.f. tietgen\"":("en route","CF Tietgen"),
"russian tea room; 150 west 57th street":("Russian Tea Room, 150 W 57th St, New York, NY 10019, US","NA"),
"gramercy park hotel; 2 lexington avenue at 21st street":("Gramercy Park Hotel, Unknown","NA"),
"hotel gramercy park; 52 gramercy park north":("Gramercy Park Hotel, Unknown","NA"),
"aboard george washington":("en route","George Washington"),
"hot springs, ar":("Hot Springs, AR, US","NA"),
"brunswick hotel, boston, ma":("Brunswick Hotel, Boston, MA, US","NA"),
"en route on board r.m.s. campania":("en route","RMS Campania"),
"st. denis hotel":("St. Denis Hotel?","NA"),
"scranton, pa":("Scranton, PA, US","NA"),
"roanoke, va":("Roanoke, VA, US","NA"),
"en route aboard s.s. coptic":("en route","SS Coptic"),
"marlborough hotel":("Marlborough Hotel?","NA"),
"berlin, germany":("Berlin, Germany","NA"),
"brooklyn,ny":("Brooklyn, NY, USA","NA"),
"en route aboard above":("en route","Unknown"),
"glenwood springs, co":("Glenwood Springs, CO, US","NA"),
"budapest, hungary":("Budapest, Hungary","NA"),
"put-in-bay island, lake erie, oh":("Put-in-Bay Island, Lake Erie, OH, US","NA"),
"buffalo,ny":("Buffalo, NY, US","NA"),
"bellevue-stratford hotel, philadelphia, pa":("Bellevue-Strafford Hotel, Philadelphia, PA, US","NA"),
"en route aboard ss.kobe maru":("en route","SS Kobe Maru"),
"s.s. zeeland":("en route","SS Zeeland"),
"st. louis":("St. Louis, MO, US","NA"),
"en route aboard scnelldampfer (express steamer) auguste victoria":("en route","SS Auguste Victoria"),
"long beach, ny":("Long Beach, New York City, New York","NA"),
"grand hotel [cincinnati, oh]":("Grand Hotel, Cincinnati, OH, US","NA"),
"aboard espress steamer auguste victoria":("en route","SS Auguste Victoria"),
"ss la champagne":("en route","SS La Champagne"),
"the bellevue-stratford, philadelphia, pa":("Bellevue-Strafford Hotel, Philadelphia, PA, US","NA"),
"s.s. kroonland":("en route","SS Kroonland"),
"south poland, me":("South Poland, ME, US","NA"),
"faneuil hall, boston, ma":("Faneuil Hall, Boston, MA, US","NA"),
"the ten eyck, albany, ny":("The Ten Eyck, Albany, NY, US","NA"),
"boston,ma.":("Boston, MA, US","NA"),
"palazzo del quirinale, rome, italy":("Palazzo del Quirinale, Rome, Italy","NA"),
"steamship north west":("en route","Steampship North West"),
"aboard paquebot la touraine":("en route","Paquebot la Touraine"),
"miami bay biscayne,fla.":("Miami Bay Biscayne, FL, US","NA"),
"waldorf-astoria, new york city":("Waldorf-Astoria, New York City, New York, US","NA"),
"hoffman house":("Hoffman House?","NA"),
"the plaza":("The Plaza?","NA"),
"114 west fourteenth street, new york":("114 W. 14th St., New York, NY, US","NA"),
"park lane; park lounge":("Park Lane; Park Lounge?","NA"),
"aboard barbarossa":("en route","SS Barbarossa"),
"nashville, [tn?]":("Nashville, TN, US","NA"),
"asheville,nc":("Asheville, NC, US","NA"),
"fifth avenue & fifty-ninth street, new york, [ny]":("Fifth Avenue & 59th St., New York, NY, US","NA"),
"toronto,ont,canada":("Toronto, Ontario, Canada","NA"),
"st.louis":("St. Louis, MO, US","NA"),
"hotel vendome [boston, ma]":("Hotel Vendome, Boston, MA, US","NA"),
"saratoga, ny":("Saratoga, NY, US","NA"),
"cleveland,ohio":("Cleveland, OH, US","NA"),
"augusta, me":("Augusta, ME, US","NA"),
"fargo, nd":("Fargo, ND, US","NA"),
"southern hotel, st. louis, mo":("Souther Hotel, St. Louis, MO, US","NA"),
"narragansett pier,r.i.":("Narragansett Pier, RI, US","NA"),
"niagara to the sea":("en route","Niagara to the Sea"),
"on board ss north land":("en route","SS North Land"),
"grand pacific hotel, chicago, il":("Grand Pacific Hotel, Chicago, IL, US","NA"),
"en route aboard new york":("en route","New York"),
"hamburg, germany":("Hamburg, Germany","NA"),
"ellicott square,buffalo,[ny?]":("Ellicott Square, Buffalo, NY, US","NA"),
"springfield,mass.":("Springfield, MA, US","NA"),
"bergen, norway":("Bergen, Norway","NA"),
"schnelldampfer furst bismarck":("en route","SS Furst Bismarck"),
"s.s. zealandia sonoma":("en route","SS Zealandia Sonoma"),
"en route to australia":("en route","Unknown"),
"en route - ss kairga":("en route","SS Kairga"),
"ss \"konigen luise\"":("en route","SS Konigin Luise"),
"bleecker street, new york":("Bleecker Street, New York, NY, US","NA"),
"66th street and broadway [ny]":("66th St and Broady, New York, NY, US","NA"),
"en route aboard s.s.vaderland":("en route","SS Vaderland"),
"fifth avenue and 59th street, new york, ny":("Fifth Avenue & 59th St., New York, NY, US","NA"),
"s.s. kinshin maru":("en route","SS Kinshin Maru"),
"hotel st. george, nyack, ny":("Hotel St. George, Nyack, NY, US","NA"),
"metropolitan opera house":("Metropolitan Opera House?","NA"),
"hotel savoy [new york]":("Hotel Savoy, New York, NY, US","NA"),
"summerville, s.c.":("Summerville, SC, US","NA"),
"new algonquin club, boston, ma":("New Algonquin Club, Boston, MA, US","NA"),
"woodstock, vt":("Woodstock, VT, US","NA"),
"new haven ct":("New Haven, CT, US","NA"),
"auditorium, chicago, il":("Auditorium Hotel, Chicago, IL, USA","NA"),
"ss graf waldersee":("en route","SS Graf Waldersee"),
"sixty-sixth street & broadway, new york, [ny]":("66th St. and Broadway, New York, NY, US","NA"),
"palm beach,fla.":("Palm Beach, FL, US","NA"),
"aboard paquebot la champagne":("en route","Paquebot la Champagne"),
"schnelidamfer auguste victoria":("en route","SS Auguste Victoria"),
"commercial club, portland, or":("Commercial Club, Portland, OR, US","NA"),
"aboard paquebot \"la savoie\"":("en route","Paquebot la Savoie"),
"young's hotel, boston, ma":("Young's Hotel, Boston, MA, US","NA"),
"hotel savoy, ny":("Hotel Savoy, New York, NY, US","NA"),
"oriental hotel, dallas, tx":("Oriental Hotel, Dallas, TX, US","NA"),
"the arlington,wash.dc":("The Arlington, Washington DC, US","NA"),
"st. charles hotel, new orleans, la":("St. Charles Hotel, New Orleans, LA, US","NA"),
"union league club, new york, ny":("Union League Club, New York, NY, US","NA"),
"rome,italy":("Rome, Italy","NA"),
"the arlington, washington, d.c.":("The Arlington, Washington DC, US","NA"),
"delmonico's, new york city":("Delmonico's, New York, NY, US","NA"),
"atlantic city,nj":("Atlantic City, NJ, US","NA"),
"hotel iroquois, buffalo, ny":("Hotel Iroquois, Buffalo, NY, US","NA"),
"hotel st. francis":("Hotel St. Francis?","NA"),
"the beaver, southern pacific":("en route","Southern Pacific"),
"l'aiglon; 13 east 55th street":("L'aiglon, 13 E 55th St.?","NA"),
"on board the ss prinz friedrich wilhelm":("en route","SS Prinz Friedrich Willhelm"),
"66 st. & b'way ny":("66 St. and Broadway, New York, NY, US","NA"),
"denver, colo.":("Denver, CO, US","NA"),
"s.s. \"southwark\"":("en route","SS Southwark"),
"maxwell house, nashville, [tn];":("Maxwell House, Nashville, TN, US","NA"),
"en route aboard ss ventura":("en route","SS Venture"),
"yokohama, japan":("Yokohama, Japan","NA"),
"naples [italy]":("Naples, Italy","NA"),
"transport":("en route","Unknown"),
"waco, tx":("Waco, TX","NA"),
"75th street and columbus ave,new york,ny":("75th St and Columbus Ave., New York, NY, US","NA"),
"117 west 34th street,new york,ny":("117 W 34th St., New York, NY, US","NA"),
"panama line,city of para":("en route","City of Para"),
"en route aboard s.s. southwark":("en route","SS Southwark"),
"66th street and broadway, new york, ny":("66th St. and Broadway, New York, NY, US","NA"),
"bway & 63rd st. ny":("Broadway and 63rd St., New York, NY, US","NA"),
"57 broad st. ny":("57 Broad St., New York, NY, US","NA"),
"aboard r.m.s. etruria":("en route","RMS Etruria"),
"s.s. southwork":("en route","SS Southwark"),
"chicago,ill":("Chicago, IL, US","NA"),
"ss trinidad":("en route","SS Trinidad"),
"66th st. & bway ny":("66th St and Broadway, New York, NY, US","NA"),
"cafe car;":("Cafe Car?","NA"),
"bermuda":("Bermuda","NA"),
"hamilton, bermuda":("Hamilton, Bermuda","NA"),
"ss southwarez":("en route","SS Southwarez"),
"adelaide, australia":("Adelaide, Australia","NA"),
"old orchard, me":("Old Orchard, ME, US","NA"),
"cleveland, ohio":("Cleveland, OH, US","NA"),
"new state house, waco, tx":("New State House, Waco, TX","NA"),
"denver, co":("Denver, CO, US","NA"),
"manhattan beach, ny":("Manhattan Beach, New York, NY","NA"),
"en route aboard ss.kohe maru":("en route","SS Kohe Maru"),
"pittsburgh, pa":("Pittsburgh, PA, US","NA"),
"en route aboard ss sierra;":("en route","SS Sierra"),
"cleveland,oh":("Cleveland, OH, US","NA"),
"143 liberty street, ny":("143 Liberty St., New York, NY","NA"),
"lucerne,switzerland":("Lucerne, Switzerland","NA"),
"columbus, ohio":("Columbus, OH, US","NA"),
"columbus,ohio":("Columbus, OH, US","NA"),
"waldorf-astoria hotel":("Waldorf-Astoria, New York City, New York, US","NA"),
"pullman dining car enroute mexico-california":("en route","Unknown"),
"waco, texas":("Waco, TX","NA"),
"manila, p.i.":("Manila, Philipines","NA"),
"dampfer \"wilhelm der grosse\"":("en route","SS Wilhelm Der Grosse"),
"steamship \"city of rio de janeiro\"":("en route","City of Rio de Janeiro"),
"en route - sonoma":("en route","Sonoma"),
"detroit,mich.":("Detroit, MI, US","NA"),
"en route aboard ss kasuga maru":("en route","SS Kasuga Maru"),
"chattanooga,tenn.":("Chattanooga, TN, US","NA"),
"en route h.h.meier":("en route","HH Meier"),
"greenfield, ma":("Greenfield, MA, US","NA"),
"mount washington, nh":("Mount Washington, NH, US","NA"),
"s.s. san juan":("en route","SS San Juan"),
"niagara falls,ny":("Niagara Falls, NY, US","NA"),
"lucerne":("Lucerne, Switzerland","NA"),
"ellicott club, buffalo, ny":("Ellicott Club, Buffalo, NY, US","NA"),
"259 bowery, new york":("256 Bowery, New York, NY, US","NA"),
"schulschiff \"herzogin sophie charlotte\"":("en route","SS Herzogin Sophie Charlotte"),
"quebec,canada":("Quebec, Canada","NA"),
"s.s. zealandia":("en route","SS Zealandia"),
"queen & crescent route,dining car cincinnati":("en route","Unknown"),
"en route aboard s.s. zeeland":("en route","SS Zeeland"),
"pawling, ny":("Pawling, NY, US","NA"),
"boylston street, boston, ma":("Boylston St., Boston, MA, US","NA"),
"hotel pontchartrain, detroit, mi":("Hotel Pontchartrain, Detroit, MI, US","NA"),
"en route aboard schnelldampfer (express steamer) auguste victoria":("en route","SS Auguste Victoria"),
"ss kobe maru":("en route","SS Kobe Maru"),
"old orchard beach, me;":("Old Orchard, ME, US","NA"),
"aboard ss chateaugay, [lake champlain, {ny}];":("en route","SS Cateaugay"),
"sonoma - second cabin":("en route","SS Sonoma"),
"enroute \"along the picturesque erie\"":("en route","Unknown"),
"r. m. s. etruria":("en route","RMS Etruria"),
"girgenti [sicily]":("Girgenti, Sicily, Italy","NA"),
"en route aboard sierra":("en route","Sierra"),
"syracuse ny":("Syracuse, NY, US","NA"),
"put-in-bay island, oh":("Put-in-Bay Island, Lake Erie, OH, US","NA"),
"malone, nj":("Malone, NJ, US","NA"),
"auditorium":("Auditorium?","NA"),
"indianapolis":("Indianapolis, IN, US","NA"),
"waldorf-astoria, new york, ny":("Waldorf-Astoria, New York City, New York, US","NA"),
"guildhall, london, england":("Guildhall, London, England","NA"),
"hotel worthy":("Hotel Worthy?","NA"),
"niagara falls, ny":("Niagara Falls, NY, US","NA"),
"hotel bellevue":("Hotel Bellevue?","NA"),
"fairmont hotel":("Fairmont Hotel?","NA"),
"the arlington":("The Arlington, Washington DC, US","NA"),
"eleventh st. and university place, new york, ny":("11 St. and University Place, New York, NY, US","NA"),
"enroute express steamer auguste victoria":("en route","SS Auguste Victoria"),
"postdampfer (mail steamer) waldersee":("en route","Postdamfer Waldersee"),
"quick lunch room, sixth avenue and 19th street, new york":("Quick Lunch Room, 6th Ave and 19th St., New York, NY, US","NA"),
"ss westernland, en route":("en route","SS Westernland"),
"enroute":("en route","Unknown"),
"columbus, oh":("Columbus, OH, US","NA"),
"the auditorium":("The Auditorium?","NA"),
"mt. pocano, pa":("Mt. Pocana, PA, US","NA"),
"fifth avenue and 59th st., ny":("5th Ave and 59 St., New York, NY","NA"),
"r.m.s.rotterdam":("en route","RMS Rotterdam"),
"trondhjem (noway?)":("Trondhjem, Norway","NA"),
"russell house, detroit, mi":("Russel House, Detroit, MI, US","NA"),
"auditorium hotel":("Auditorium Hotel, Chicago, IL, USA","NA"),
"bellevue-stratford, philadelphia, pa":("Bellevue-Strafford Hotel, Philadelphia, PA, US","NA"),
"hotel rennert":("Hotel Rennert?","NA"),
"worcester, ma":("Worcester, MA, US","NA"),
"watch hill, ri":("Watch Hill, RI, US","NA"),
"laurel-in-the-pines, lakewood, nj":("Laurel-in-the-Pines, Lakewood, NJ, US","NA"),
"the waldorf [new york, ny]":("The Waldorf, New York, NY, US","NA"),
"23rd street, new york":("23rd St., New York, NY, US","NA"),
"metropolitan hotel, new york, ny":("Metropolitan Hotel, New York, NY, US","NA"),
"hotel majestic, philadelphia, pa":("Hotel Majestic, Philadelphia, PA, US","NA"),
"hotel marlborough, new york, ny":("Hotel Marlborough, New York, NY, US","NA"),
"adirondacks, ny":("Adironbacks, New York, NY, US","NA"),
"minnewaska,ny;":("Minnewaska, New York, NY, US","NA"),
"colombo, (?)":("Colombo?","NA"),
"en route steamer august victoria":("en route","SS Auguste Victoria"),
"horticultural hall, philadelphia, pa":("Horticultural Hall, Philiadelphia, PA, US","NA"),
"hotel del campidoglio, new york, ny":("Hotel del Campidoglio, New York, NY, US","NA"),
"terrace garden":("Terrace Garden?","NA"),
"en route \"statendam\"":("en route","Statendam"),
"union square, new york, ny":("Union Square, New York, NY, US","NA"),
"r.m.s. rotterdam":("en route","RMS Rotterdam"),
"r.m.s. empress of india":("en route","RMS Empress of India"),
"petoskey, mi;":("Petoskey, MI, US","NA"),
"the hollenden, cleveland, oh":("The Hollenden, Cleveland, OH, US","NA"),
"park row bldg. [ny]":("Park Row Building, New York, NY, US","NA"),
"new tontine hotel, new haven [ct]":("New Tontine Hotel, New Haven, CT, US","NA"),
"the raleigh, washington, dc":("The Raleigh, Washingon D.C., US","NA"),
"residence-palais, copenhagen, denmark":("Residence-Palais, Copenhagen, Denmark","NA"),
"[st.louis,mo?]":("St. Louis, MO, US","NA"),
"montauk club, brooklyn, ny":("Montauk Club, Brooklyn, NY,US","NA"),
"new york zoological park":("New York Zoological Park, NY, US","NA"),
"57 broad street, new york, [ny]":("57 Broad St., New York, NY, US","NA"),
"windsor castle, england":("Windsor Castle, England","NA"),
"old point comfort,va":("Old Point Comfort, VA, US","NA"),
"milwaukee,wi":("Milwaukee, WI, US","NA"),
"manhattan hotel,ny":("Manhattan Hotel, New York, NY, US","NA"),
"trocadero":("Trocadero?","NA"),
"broadway and 23rd street, ny":("Broadway and 23rd St., NY, US","NA"),
"mercantile club (st louis, mo)":("Mercantile Club, St. Louis, MO, US","NA"),
"pennsylvania railroad dining cars en route new york to chicago":("en route","Unknown"),
"auguste victoria":("en route","SS Auguste Victoria"),
"delmonico's,[new york,ny?]":("Delmonico's, New York, NY, US","NA"),
"en route washington-atlanta":("en route","Washington-Atlanta"),
"copenhagen":("Copenhagen, Denmark","NA"),
"havana, cuba":("Havana, Cuba","NA"),
"pullman car":("en route","Unknown"),
"delmonico,[ny]":("Delmonico's, New York, NY, US","NA"),
"hotel d'angleterre":("Hotel D'Angleterre?","NA"),
"frankfurter stubb":("Frankfurter Stubb?","NA"),
"restaurant la corvette":("Restaurant La Corvette?","NA"),
"tadich grill; 545 clay street":("Tadich Grill, 545 Clay St.?","NA"),
"maurice":("Maurice?","NA"),
"franziskaner":("Franziskaner?","NA"),
"the mandarin, garfield 6464":("The Mandarin, Garfield 6464?","NA"),
"the feather river route":("The Feather River Route?","NA"),
"hotel del monte":("Hotel del Monte?","NA"),
"general mess":("General Mess?","NA"),
"on board the kronprinzessin cecilie":("en route","Kronprinzessin Cecile"),
"aboard u.s.m.s. st. louis":("en route","USMS St. Louis")}
    
    if x in manualClean: return manualClean[x][key]
    elif x == "": return x
    else: return "Unclean"

# Finally add the new columns to the data frame and write it back out as CSV
menu["placeClean"] = menu['place'].apply(lambda x: cleanPlace(x, 0))
menu["vesselName"] = menu['place'].apply(lambda x: cleanPlace(x, 1))
menu["meal"] = menu['event'].apply(mapEventToMeal)
menu["cleanedVenue"] = menu['venue'].apply(mapVenueToCleanVenue)

# Change the date information to ISO format
for item in menu['date']:
    if(item!='' and item[2]=='/'):
        menu['date'].replace(item, ''+item[-4:]+'-'+item[3:5]+'-'+item[0:2],inplace=True)
print(menu)

menu.to_csv("p02_menu_cleaned.csv.gz", compression='gzip', index = False)