# When we autogenerate YES WORKFLOWS
#  the script uses temporary table names table0, table1, etc.
#  but because we have multiple workflows we need
#  to make sure the table names are unique.

# The following script will go through the 4 autogenerated tables
#  and make sure the table names are unique.
# It does this by renumbering the tables.

import re
import sys

# From file _in,
# renumbers tableNN to table{NN+_start}
# Writes file _out
# Returns the maximum NN encountered
def renumber(_in, _out, _start):
    pat = re.compile("(table)(\d+)")

    def renumber_internal(match):
        g = match.groups()
        return g[0] + str(int(g[1]) + _start)

    outL = []
    maxNN = None
    inL = open(_in, 'r').readlines()

    # Find max number
    for L in inL:
        tups = pat.findall(L)
        for t in tups:
            if maxNN == None: maxNN = int(t[1])
            elif t[1] > maxNN: maxNN = int(t[1])
        
        # Use same regexp to replace with higher table number
        # Uses subfunction declared above
        outL.append(pat.sub(renumber_internal, L))

    with open(_out, 'w') as out:
        out.writelines(outL)
    
    return maxNN

n = renumber(sys.argv[1], sys.argv[2], int(sys.argv[3]))
print(n)
